// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfveltufyvsejoqvbrzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdmVsdHVmeXZzZWpvcXZicnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTEyNTUsImV4cCI6MjA2MTA4NzI1NX0.SttdwOk49CHCQYPlhEklgqTImZoE9KoZy8yapU-FCCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);